services:
  directus:
    image: directus/directus:12.5.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/database
      - ./uploads:/directus/uploads
      - ./extensions:/extensions
    env_file:
      - ../.env  
